### ISSUE TITLE
Cannot add synchronized volume sequence to browser when its master sequence is a transform sequence

### ISSUE THREAD

**Issue by moselhy** [SlicerRt/Sequences#33]
To reproduce this issue:

1. Open Slicer
2. Load CTP-cardio sample sequence from Sample Data module
3. Load [this MRB of Transforms](http://slicer.kitware.com/midas3/download/item/305153/OutputTransforms.mrb)
4. Create a new sequence
5. Add all the transforms to the new sequence
6. Try to create a browser node (not using the Python interactor) to synchronize with both the volume and transform sequences

**Comment by matthewsholden** [comment]
Could you please verify that the index types for your two sequences are the same (look in the Sequences module, just under the sequence node selector)? If the index types are different, you cannot add the two sequences to the same sequence browser.

When I load the CTP-cardio dataset, its index type is "frame".

When I manually add your transforms into a new sequence node, its index type is "time (s)" by default.

These two sequences cannot be added to the same sequence browser node because of the different index types. You will see a warning in the Slicer log if you try.

If I change the index type of the transform sequence to "frame" (using the Sequences module), then I can add them both to the same sequence browser.

**Comment by moselhy** [comment]
Ah, I see. Nice catch!

However, I think that as long as the number of data nodes are the same, a Sequence Browser should be able to synchronize with any Sequences despite the index type. What do you think?

**Comment by matthewsholden** [comment]
What is your application for which you would like to have synchronized sequences with different index types?

I don't know if allowing this makes sense from a semantic standpoint. If it is not possible to find a common index for two sequences, then I suggest that they shouldn't be synchronized.

But I welcome the opinions of others on this.

**Comment by moselhy** [comment]
It's the transforms for the volume sequence. However, when the transform sequence is saved, it is stored as a "MRB" file which must be manually put into a sequence. And this is why the index type is set to the default when it is loaded, when it is really supposed to be "frame".

**Comment by matthewsholden** [comment]
Note that if you save the entire scene, the entire Sequence Browser node will be preserved. This may be useful for you.

But I wonder if addressing #13 would better solve your problem? If we added a way of exporting an entire Sequence Browser node, all of the synchronized sequences would be maintained in the Sequence Browser node.

**Comment by moselhy** [comment]
Yes I think that would solve the problem

On Aug 23, 2017, at 8:53 AM, Matthew Holden <notifications@github.com<mailto:notifications@github.com>> wrote:


Note that if you save the entire scene, the entire Sequence Browser node will be preserved. This may be useful for you.

But I wonder if addressing #13<https://github.com/SlicerRt/Sequences/issues/13> would better solve your problem? If we added a way of exporting an entire Sequence Browser node, all of the synchronized sequences would be maintained in the Sequence Browser node.

**Comment by matthewsholden** [comment]
Ok, thanks for the info. I will look into it.

**Comment by lassoan** [comment]
Sequences feature has been moved to Slicer-4.11 core. All issues are tracked in 3D Slicer's issue tracker.
