### ISSUE TITLE
.seq.mhd voxel spacing for image data vs. volume node

### ISSUE THREAD

**Issue by RMR54** [SlicerRt/Sequences#62]
If saving out tracked ultrasound frames as .MHD, we can update the "ElementSpacing" header info from "1 1 1", to spacing values as specified in Seq_Frame000#_ElementSpacing, to load it into Slicer with the right spacing. 

If "ElementSpacing" in .seq.mhd is modified, on the other hand, then it appears that the image data gets updated with pixel spacing, and not the proxy node at each index. This causes issues with `vtkMRMLSliceLogic`'s `FitSliceToAll()`. So the volume appears very small, if I click on the shown icon in the slice widget controller:

![image](https://user-images.githubusercontent.com/8135181/48205143-affc7900-e339-11e8-9cbc-110a09f89315.png)

I tested with loading in MHDs (just volumes, not sequences), and the same issue occurs if the image data voxel spacing is changed (& the vtkMRMLVolumeNode's spacing is kept at 1, 1, 1). 
I've seen [comments here](https://github.com/Slicer/Slicer/blob/da6ad88dba4d60b7784953b01e82c5dd21670503/Libs/MRML/Core/vtkMRMLVolumeNode.h#L163-L172
) regarding pixel data set to the ImageData object.

On reading Sequence MetaFile Images, should the spacing be set to the proxy node at each index instead of [applying it to ImageData object](https://github.com/SlicerRt/Sequences/blob/ea6ce4b80c41160aceb1cbea52a858973a25fa9e/MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx#L182)?

**Comment by lassoan** [comment]
Plus sequence files contain tracked image data that may have temporally changing geometry (position, orientation, scaling). Since .mha and .nrrd files could only store a single geometry, we don't use the standard fields for storing image geometry, but store transforms in custom fields instead. Currently these files use simply .mha or .nrrd file name extension but we will soon switch to use .igs.mha and .igs.nrrd extension to make this difference very clear.

Volume sequence files are simple 4D volumes that cannot change their position or geometry in time. Position, spacing, and axis directions are stored in the image header in standard fields.

**Comment by lassoan** [comment]
> On reading Sequence MetaFile Images, should the spacing be set to the proxy node at each index instead of applying it to ImageData object?

Normally, if you acquire tracked image data then you have access to ImageToReference or similar transform sequence saved in the same file. Apply the proxy node of this transform sequence to the proxy node of the image sequence to see the image moving in space. If you have an ImageToProbe calibration transform and a ProbeToReference tracker transform then you need to concatenate these transforms (apply ImageToProbe to the Image node; aply ProbeToReference to the ImageToProbe node).

**Comment by RMR54** [comment]
Thanks for the clarification @lassoan. When checking with "Volumes" module, it looks like proxy nodes spacing gets updated at each frame. This happens even if I harden transform. Should the transform be applied to the proxy node, at each frame/index value?

**Comment by RMR54** [comment]
> Apply the proxy node of this transform sequence to the proxy node of the image sequence to see the image moving in space

@lassoan, does the transform have to be applied to the proxy node at each index value of the sequence of the image sequence?

**Comment by lassoan** [comment]
To harden a transform on a volume sequence, you need to harden the transform on each sequence item. 

How to apply transforms to nodes. "Crop volume sequence" module does something very similar, you can modify a couple of lines in it to [apply transform](https://www.slicer.org/wiki/Documentation/Nightly/Modules/Transforms#Examples) instead of crop.

If you have usable solution then it would be great if you could contribute it back to Sequences extension.
